<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Standard Error from JUnitTclTest</title>
</head>
<body>
<pre>java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: java.lang.RuntimeException: Normally, we would exit here because Manager.exitAfterWrapup() was called.  However, because the ptolemy.ptII.exitAfterWrapup property is set, we throw this exception instead.
	at ptolemy.util.StringUtilities.exit(StringUtilities.java:363)
	at ptolemy.actor.Manager.wrapup(Manager.java:1531)
	at ptolemy.actor.Manager.execute(Manager.java:407)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
Warning: '.top.test' is in training mode, set the trainingMode parameter to false before checking in
Warning: '.top.test' is in training mode, set the trainingMode parameter to false before checking in
Warning: '.top.test' is in training mode, set the trainingMode parameter to false before checking in
Warning: '.BooleanSwitch_RegressionTest_WrongTrainingValues.Test' is in training mode, set the trainingMode parameter to false before checking in
Warning: '.BooleanSwitch_RegressionTest_WrongTrainingValues.Test2' is in training mode, set the trainingMode parameter to false before checking in
Warning: '.BooleanSwitch_RegressionTest_WrongTrainingValues.Test2' The test produced 0 tokens.
Warning: '.top.testExceptionHandler' is in training mode, set the trainingMode parameter to false before checking in
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: PublisherPorts cannot be used at the top level, use a Publisher actor instead.
  in .PublisherPortToplevelSubscriber.PublisherPort
	at ptolemy.actor.PublisherPort.preinitialize(PublisherPort.java:403)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1769)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ptolemy.util.test.junit.AutoKnownFailedTests.RunModel(AutoKnownFailedTests.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
Caused by: ptolemy.kernel.util.IllegalActionException: PublisherPorts cannot be used at the top level, use a Publisher actor instead.
  in .PublisherPortToplevelSubscriber.PublisherPort
	at ptolemy.actor.PublisherPort.preinitialize(PublisherPort.java:403)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1769)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: SubscriberPorts cannot be used at the top level, use a Subscriber actor instead.
  in .PublisherSubscriberPortToplevel.SubscriberPort
	at ptolemy.actor.SubscriberPort.preinitialize(SubscriberPort.java:328)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1769)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ptolemy.util.test.junit.AutoKnownFailedTests.RunModel(AutoKnownFailedTests.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
Caused by: ptolemy.kernel.util.IllegalActionException: SubscriberPorts cannot be used at the top level, use a Subscriber actor instead.
  in .PublisherSubscriberPortToplevel.SubscriberPort
	at ptolemy.actor.SubscriberPort.preinitialize(SubscriberPort.java:328)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1769)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: SubscriptionAggregatorPorts cannot be used at the top level, use a SubscriptionAggregator actor instead.
  in .PublisherSubscriptionAggregatorPort.SubscriptionAggregatorPort
	at ptolemy.actor.SubscriptionAggregatorPort.preinitialize(SubscriptionAggregatorPort.java:353)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1769)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ptolemy.util.test.junit.AutoKnownFailedTests.RunModel(AutoKnownFailedTests.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
Caused by: ptolemy.kernel.util.IllegalActionException: SubscriptionAggregatorPorts cannot be used at the top level, use a SubscriptionAggregator actor instead.
  in .PublisherSubscriptionAggregatorPort.SubscriptionAggregatorPort
	at ptolemy.actor.SubscriptionAggregatorPort.preinitialize(SubscriptionAggregatorPort.java:353)
	at ptolemy.actor.CompositeActor.preinitialize(CompositeActor.java:1769)
	at ptolemy.actor.Manager.preinitializeAndResolveTypes(Manager.java:1040)
	at ptolemy.actor.Manager.initialize(Manager.java:710)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: TypeTest actor has no training data.
  in .sizedarray3.TypeTest
	at ptolemy.actor.lib.TypeTest.initialize(TypeTest.java:250)
	at ptolemy.actor.Director.initialize(Director.java:938)
	at ptolemy.actor.Director.initialize(Director.java:907)
	at ptolemy.actor.sched.StaticSchedulingDirector.initialize(StaticSchedulingDirector.java:159)
	at ptolemy.domains.sdf.kernel.SDFDirector.initialize(SDFDirector.java:544)
	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:935)
	at ptolemy.actor.Manager.initialize(Manager.java:724)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ptolemy.util.test.junit.AutoKnownFailedTests.RunModel(AutoKnownFailedTests.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at junitparams.internal.InvokeParameterisedMethod.evaluate(InvokeParameterisedMethod.java:102)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
Caused by: ptolemy.kernel.util.IllegalActionException: TypeTest actor has no training data.
  in .sizedarray3.TypeTest
	at ptolemy.actor.lib.TypeTest.initialize(TypeTest.java:250)
	at ptolemy.actor.Director.initialize(Director.java:938)
	at ptolemy.actor.Director.initialize(Director.java:907)
	at ptolemy.actor.sched.StaticSchedulingDirector.initialize(StaticSchedulingDirector.java:159)
	at ptolemy.domains.sdf.kernel.SDFDirector.initialize(SDFDirector.java:544)
	at ptolemy.actor.CompositeActor.initialize(CompositeActor.java:935)
	at ptolemy.actor.Manager.initialize(Manager.java:724)
	at ptolemy.actor.Manager.execute(Manager.java:356)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: Expected:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute
But got:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute========

  in .TestExceptionAttribute1
Because:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute
  in .TestExceptionAttribute1.TestExceptionAttribute
Because:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute========

  in .TestExceptionAttribute1
Because:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute
	at ptolemy.actor.lib.TestExceptionAttribute.handleException(TestExceptionAttribute.java:174)
	at ptolemy.actor.Manager.execute(Manager.java:476)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
Caused by: ptolemy.kernel.util.IllegalActionException: Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute========

  in .TestExceptionAttribute1
Because:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2780)
	at ptolemy.actor.Manager.wrapup(Manager.java:1512)
	at ptolemy.actor.Manager.execute(Manager.java:407)
	... 2 more
Caused by: ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute1.TestExceptionAttribute
	at ptolemy.actor.lib.TestExceptionAttribute.wrapup(TestExceptionAttribute.java:213)
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2705)
	... 4 more
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: Expected:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute
But got:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute========
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute2========

  in .TestExceptionAttribute2
Because:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute
  in .TestExceptionAttribute2.TestExceptionAttribute
Because:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute========
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute2========

  in .TestExceptionAttribute2
Because:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute
	at ptolemy.actor.lib.TestExceptionAttribute.handleException(TestExceptionAttribute.java:174)
	at ptolemy.actor.Manager.execute(Manager.java:476)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
Caused by: ptolemy.kernel.util.IllegalActionException: Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute========
ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute2========

  in .TestExceptionAttribute2
Because:
 was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2780)
	at ptolemy.actor.Manager.wrapup(Manager.java:1512)
	at ptolemy.actor.Manager.execute(Manager.java:407)
	... 2 more
Caused by: ptolemy.kernel.util.IllegalActionException:  was initialized and should have handled an exception but did not see any.
  in .TestExceptionAttribute2.TestExceptionAttribute
	at ptolemy.actor.lib.TestExceptionAttribute.wrapup(TestExceptionAttribute.java:213)
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2705)
	... 4 more
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: Expected:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler
But got:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler========

  in .TestExceptionHandler1
Because:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler
  in .TestExceptionHandler1.TestExceptionHandler
Because:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler========

  in .TestExceptionHandler1
Because:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler
	at ptolemy.actor.lib.TestExceptionHandler.handleException(TestExceptionHandler.java:142)
	at ptolemy.actor.Manager.execute(Manager.java:476)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
Caused by: ptolemy.kernel.util.IllegalActionException: Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler========

  in .TestExceptionHandler1
Because:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2780)
	at ptolemy.actor.Manager.wrapup(Manager.java:1512)
	at ptolemy.actor.Manager.execute(Manager.java:407)
	... 2 more
Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler

  in .TestExceptionHandler1.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler
	at ptolemy.actor.Director.wrapup(Director.java:1736)
	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1527)
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2768)
	... 4 more
Caused by: ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler1.TestExceptionHandler
	at ptolemy.actor.lib.TestExceptionHandler.wrapup(TestExceptionHandler.java:168)
	at ptolemy.actor.Director.wrapup(Director.java:1722)
	... 6 more
java.lang.RuntimeException: Execution failed
	at ptolemy.moml.MoMLSimpleApplication$UnloadThread.run(MoMLSimpleApplication.java:402)
Caused by: ptolemy.kernel.util.IllegalActionException: Expected:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
But got:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler========

  in .TestExceptionHandler2
Because:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
  in .TestExceptionHandler2.TestExceptionHandler
Because:
Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler========

  in .TestExceptionHandler2
Because:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
	at ptolemy.actor.lib.TestExceptionHandler.handleException(TestExceptionHandler.java:142)
	at ptolemy.actor.Manager.execute(Manager.java:476)
	at ptolemy.actor.Manager.run(Manager.java:1263)
	at ptolemy.actor.Manager$PtolemyRunThread.run(Manager.java:1915)
Caused by: ptolemy.kernel.util.IllegalActionException: Exception(s) thrown during wrapup:
ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler========

  in .TestExceptionHandler2
Because:
Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2780)
	at ptolemy.actor.Manager.wrapup(Manager.java:1512)
	at ptolemy.actor.Manager.execute(Manager.java:407)
	... 2 more
Caused by: ptolemy.kernel.util.IllegalActionException: Exceptions occurred during wrapup:
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler2

  in .TestExceptionHandler2.DE Director
Because:
 should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
	at ptolemy.actor.Director.wrapup(Director.java:1736)
	at ptolemy.domains.de.kernel.DEDirector.wrapup(DEDirector.java:1527)
	at ptolemy.actor.CompositeActor.wrapup(CompositeActor.java:2768)
	... 4 more
Caused by: ptolemy.kernel.util.IllegalActionException:  should have handled an exception but did not see any.
  in .TestExceptionHandler2.TestExceptionHandler
	at ptolemy.actor.lib.TestExceptionHandler.wrapup(TestExceptionHandler.java:168)
	at ptolemy.actor.Director.wrapup(Director.java:1722)
	... 6 more
</pre>
</body>
</html>
